// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIfConfigExists() {
  return window['go']['backend']['App']['CheckIfConfigExists']();
}

export function EntryConfig(arg1) {
  return window['go']['backend']['App']['EntryConfig'](arg1);
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}
